### ISSUE TITLE
Having problems enabling push mode with ViewMenuUI in 8.3

### ISSUE THREAD

**Issue by fschon** [mstahv/cdi-helpers#10] opened 2018-02-15 08:59 UTC
I get the below exception. Is @Push mode supported on ViewMenuUI? When disabling push there are no errors. 

09:51:28,802 SEVERE [com.vaadin.server.DefaultErrorHandler] (default task-18) : 
java.lang.NoSuchMethodError: com.vaadin.ui.Notification.show(Ljava/lang/String;Lcom/vaadin/ui/Notification$Type;)V
        at org.vaadin.cdiviewmenu.ViewMenuUI.handleNavigationError(ViewMenuUI.java:64)
        at org.vaadin.cdiviewmenu.ViewMenuUI$1.navigateTo(ViewMenuUI.java:36)
        at org.vaadin.cdiviewmenu.ViewMenu.navigateTo(ViewMenu.java:339)
        at org.vaadin.cdiviewmenu.ViewMenu.navigateTo(ViewMenu.java:312)

Servlet parms:
@WebServlet(
        asyncSupported = true,
        urlPatterns = "/*",
        initParams = {
                @WebInitParam(name = Constants.SERVLET_PARAMETER_PRODUCTION_MODE, value = "false"),
                @WebInitParam(name = Constants.SERVLET_PARAMETER_PUSH_MODE, value = "true")
        })

**Comment by mstahv** [comment] 2018-02-28 08:53
That looks like some version conflict. Do you have an example project where the issue can be reproduced?

**Comment by mstahv** [comment] 2018-02-28 08:53
I think this is the same as #9 ?

**Comment by mstahv** [comment] 2018-04-07 06:09
Hi, can you try with the latest version (2.3)? I hope this is now fixed. If not, get back to me with a project where this can be reproduced.

**Closed as completed by mstahv** 2018-04-07 06:09 UTC
